USE VIDEO;

DROP TABLE IF EXISTS `TB_CODE`;
CREATE TABLE `TB_CODE` (
	`CODE_ID` VARCHAR(30) NOT NULL , 
	`CODE_NM` VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL , 
	`USE_AT` VARCHAR(1) DEFAULT 'Y' , 
	`DEL_AT` VARCHAR(1) DEFAULT 'N' ,
	`REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY ( `CODE_ID` )
);


DROP TABLE IF EXISTS `TB_VIDEO`;
CREATE TABLE `TB_VIDEO` (
	`VIDEO_ID`         VARCHAR(30) NOT NULL ,
	`PARENT_VIDEO_ID`        VARCHAR(30) NULL ,
	`VIDEO_TYPE_CODE`        VARCHAR(30) NULL ,
	`VIDEO_NM`        VARCHAR(200) COLLATE utf8_unicode_ci NULL ,
	`VIDEO_EXPLAIN`        VARCHAR(500) COLLATE utf8_unicode_ci NULL ,
	`VIDEO_ACTOR`        VARCHAR(200) COLLATE utf8_unicode_ci NULL ,
	`VIDEO_PATH`        VARCHAR(500) COLLATE utf8_unicode_ci NULL ,
	`USE_AT`        VARCHAR(1) DEFAULT 'Y' ,
	`DEL_AT`        VARCHAR(1) DEFAULT 'N' ,
	`REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (`VIDEO_ID`)        
);

DROP TABLE IF EXISTS `TB_VIDEO_GENRE`;
CREATE TABLE `TB_VIDEO_GENRE` (
	`VIDEO_ID`         VARCHAR(30) NOT NULL ,
	`GENRE_CODE`        VARCHAR(100) NOT NULL ,
	`REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (`VIDEO_ID`,`GENRE_CODE`) 
);


DROP TABLE IF EXISTS `TB_VIDEO_VIEW_INFO`;
CREATE TABLE `TB_VIDEO_VIEW_INFO` (
	`VIDEO_ID`         VARCHAR(30) NOT NULL ,
	`COUNT`        INT DEFAULT 0 NOT NULL ,
	`GOOD`        INT DEFAULT 0 NOT NULL ,
	`BAD`        INT DEFAULT 0 NOT NULL ,
	`REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	PRIMARY KEY (`VIDEO_ID`) 
);

DROP TABLE IF EXISTS `TB_CONTENT`;
CREATE TABLE `TB_CONTENT` (
	`CONTENT_ID`   VARCHAR(30) NOT NULL ,
	`PARENT_CONTENT_ID` VARCHAR(30) NULL ,
	`VIDEO_ID` VARCHAR(30) NULL ,
	`CONTENT_NM`   VARCHAR(100) COLLATE utf8_unicode_ci  NULL , 
	`CONTENT_TYPE` VARCHAR(30) NOT NULL , 
	
	`SORT_SN` INT DEFAULT 99 NOT NULL ,
	`REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	`USE_AT` VARCHAR(1) DEFAULT 'Y' ,
	`DEL_AT` VARCHAR(1) DEFAULT 'N' ,
	PRIMARY KEY (`CONTENT_ID`) 
);

DROP TABLE IF EXISTS `TB_MY_RECENT_VIDEO`;
CREATE TABLE `TB_MY_RECENT_VIDEO` (
	`USER_ID` VARCHAR(30) NOT NULL , 
	`VIDEO_ID` VARCHAR(30) NOT NULL ,
	
	`REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	`UPD_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	`USE_AT` VARCHAR(1) DEFAULT 'Y' ,
	`DEL_AT` VARCHAR(1) DEFAULT 'N' ,
	PRIMARY KEY (`USER_ID`,`VIDEO_ID`) 
);